services:
  mongo:
    image: mongo:7.0
    container_name: search_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-rootpass}
      MONGO_INITDB_DATABASE: searchdb
    volumes:
      - mongo_data:/data/db
      - ./backend/src/BD/init:/docker-entrypoint-initdb.d:ro

  mongo-express:
    image: mongo-express:latest    # Cambiado a latest
    container_name: search_mongo_express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USER:-root}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD:-rootpass}
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      - mongo

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: search_backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://search_user:search_pass@mongo:27017/searchdb?authSource=searchdb
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo

volumes:
  mongo_data: